#- repo: local
#  hooks:
#    - id: django-makemigrations
#      name: django-makemigrations
#      entry: ./hook-makemigrations.sh
#      always_run: true
#      verbose: true
#      language: script

- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
    - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0  # Use the ref you want to point at
  hooks:
    - id: autopep8-wrapper
      args: ['--in-place', '--aggressive', '--aggressive']
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
      args: ['--unsafe']
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: ['--fix=auto']
    - id: name-tests-test
      args: ['--django']
    - id: pretty-format-json
      args: ['--autofix']
    - id: flake8
