---

version: '3.4'
services:
  mail:
    image: djfarrelly/maildev:1.1.0
    ports:
      - 1080:80

  postgres:
    image: postgres:11
    env_file: .env.stage
    ports:
      - 5432:5432
    volumes:
      - ../volumes/pgdata:/var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./service/
    depends_on:
      - redis
      - postgres
    env_file:
      - .env.stage
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:8000}:8000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    command: bash start.sh
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  worker:
    build:
      context: ./service/
    command: celery -A core worker -l info
    depends_on:
      - web
      - redis
    env_file:
      - .env.stage
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  redis:
    image: redis:5.0.8-alpine
    env_file: .env.stage
    command: "redis-server --appendonly yes --requirepass 1234567Q"

  nginx:
    build: ./nginx
    env_file: .env.stage
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./service/static/:/app/static
      - ./service/media/:/app/media
      - ./service/logs/:/app/logs
