---

version: '3.4'
services:
  mail:
    image: djfarrelly/maildev:1.1.0
    ports:
      - 1080:80

  postgres:
    image: postgres:11
    env_file: .env.dev
    ports:
      - 5432:5432
    volumes:
      - ../volumes/pgdata:/var/lib/postgresql/data/pgdata

  worker:
    build:
      context: ./service/
    command: celery worker -A core -l info
    depends_on:
      - redis
    env_file:
      - .env.test
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  redis:
    image: redis:5.0.8-alpine
    env_file: .env.dev
    command: "redis-server --appendonly yes --requirepass 1234567Q"
