# Generated by Django 3.0.4 on 2020-03-09 16:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('title',
                 models.CharField(
                     max_length=255,
                     verbose_name='Title')),
                ('body',
                 models.TextField(
                     verbose_name='Body')),
                ('location',
                 models.CharField(
                     max_length=255,
                     verbose_name='Location')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('target_date',
                 models.DateTimeField(
                     verbose_name='Date')),
                ('completed',
                 models.BooleanField(
                     default=False)),
                ('celery_task_id',
                 models.CharField(
                     blank=True,
                     max_length=255)),
                ('owner',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='reminders',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Owner')),
                ('participants',
                 models.ManyToManyField(
                     blank=True,
                     related_name='participants',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': (
                    '-pk',
                ),
            },
        ),
    ]
