# Generated by Django 3.0.4 on 2020-03-10 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='participants',
            field=models.ManyToManyField(
                blank=True,
                related_name='reminder_participants',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='target_date',
            field=models.DateTimeField(
                verbose_name='Target date'),
        ),
    ]
