# Generated by Django 3.0.5 on 2020-04-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_related_and_verbose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={},
        ),
    ]
